### ISSUE TITLE
This repo needs a pinned node version

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/paxcounterthf-collector#5]
please use [nvm](https://github.com/nvm-sh/nvm) 

- then `nvm install lts/erbium`
- and `nvm current > .nvmrc`
- The devDependency `@types/node` points to a version for v13 this also needs some fixing. `npm install @types/node@^12.0.0`

**Comment by julizet** [comment]
added the .nvmrc file with this commit 189a2f00d7f31b4200282078d1d4ee271fcf7f8d

**Comment by julizet** [comment]
downgraded the devDependency witht this commit c97fbbb8fe2f7eb9b6fe7dc1808360bf64f6ff0c
